"""Add warmup_sessions and farming_sessions tables

Revision ID: a6373c67a421
Revises: 88c2468f075b
Create Date: 2026-03-16 20:48:56.877353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6373c67a421'
down_revision: Union[str, None] = '88c2468f075b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
